\i ./table_entity.sql
\i ./table_catalog.sql
\i ./table_client.sql
\i ./table_address.sql
\i ./index_address_primary.sql
\i ./function_create_entity.sql
\i ./function_create_catalog.sql
\i ./function_create_client.sql
\i ./function_add_address.sql
\i ./function_update_entity.sql
\i ./function_delete_entity.sql
\i ./function_update_catalog.sql
\i ./function_delete_catalog.sql
\i ./function_update_client.sql
\i ./function_delete_client.sql
\i ./function_update_address.sql
\i ./function_delete_address.sql
\i ./seed_initial_data.sql
